# Forcing a new build on Oct 15
[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200