[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates" # The folder with your index.html

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200